Clarify mandate of htimedelta
riscv/riscv-isa-manual pull request #1486
Opened 2024-07-01 09:03 UTC by cebarobot

According to #481, htimedelta CSR is tide with time CSR. Implementations should either implement both CSRs or skip both.

2024-07-01 15:10 UTC, allenjbaum commented
Typo: tide -> tied

On Mon, Jul 1, 2024 at 2:15 AM Xu, Zefan ***@***.***> wrote:

> XiangShan <https://github.com/OpenXiangShan/XiangShan> does not implement
> the time CSR (really high cost) but does implement the htimedelta CSR
> (almost no cost). It takes us a long time to notice that this led to
> opensbi emulating the time CSR incorrectly, which causes failure in the
> virtual machine time interrupts.
>
> I hope this patch will clarfy when htimedelta should be implemented, to
> prevent others trap into the same problem.
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/riscv/riscv-isa-manual/pull/1486#issuecomment-2199641168>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AHPXVJSFY2CKZ4NEE55M2KTZKEM2TAVCNFSM6AAAAABKFEHNFKVHI2DSMVQWIX3LMV43OSLTON2WKQ3PNVWWK3TUHMZDCOJZGY2DCMJWHA>
> .
> You are receiving this because you are subscribed to this thread.Message
> ID: ***@***.***>
>

2024-07-01 23:51 UTC, aswaterman commented
I think the proposed change contradicts current behavior.  If `mcounteren`.TM=0, then HS-mode accesses to `time` will trap, which might ultimately result in a visible trap to HS-mode.  However, `htimedelta` is not conditioned on `mcounteren`.TM.  So it is indeed possible for `htimedelta` to exist from HS-mode's perspective even when `time` doesn't.

2024-07-02 05:02 UTC, aswaterman commented
Disagreed. The hypervisor extension chapter is written from the perspective of HS-mode. From that perspective, there is no difference between whether the time CSR is physically implemented or is disabled by mcounteren.

2024-07-02 05:05 UTC, aswaterman commented
I would be OK if you deleted the “conversely” clause and kept only the first part.

2024-07-02 05:05 UTC, aswaterman requested changes
Putting a hold on this PR until the discussion is resolved.

2024-07-03 02:51 UTC, aswaterman commented
Merged manually via 257e5ca096725b1fabc73f674a9a780d76e3e7fc

2024-07-03 02:51 UTC, closed without merging