Fix immediate types font size
riscv/riscv-isa-manual pull request #1620
Opened 2024-08-31 18:24 UTC by HepoH3

The font size is inconsistent between different types of immediates in the figure below (compare the b and j-types with the others):

<details>

<summary> current figure 2.3 </summary>

![firefox_loANPOHf8l](https://github.com/user-attachments/assets/9e852c08-5228-4024-b177-eb11a24e43cf)

</details>

This might have been done intentionally, but in the next figure, all types have the 'fontsize: 12' setting. Note that even with this size, the brackets of some fields still collide with the bit borders. I've checked at which size the collision doesn't occur, and that size is 10 (in this figure, all types use size 11, except for the j-type, which uses size 10):

<details>

<summary> figure 2.3 size experiments</summary>

![firefox_sx1Cbkmblp](https://github.com/user-attachments/assets/7249c20d-725e-40e0-a9d8-a37712655cd6)

</details>

However, I don't think it's worth changing.

---

Additionally, I want to bring to your attention an issue with figure names. Most of them are missing now, even though they were present in the v20191213 version. However, there's a strange figure name in Figure 2.4:

<details>

<summary> current figure 2.4 </summary>

![firefox_oUiqUJrxA8](https://github.com/user-attachments/assets/1a67629f-2e35-4e16-9494-28e97f256fbf)

</details>

It appears in an odd location with a strange number. I'm not sure how these names are generated, so I can't fix it myself.

2024-08-31 23:03 UTC, aswaterman requested changes
IIRC, the issue is that the `[11]` in the B-type and J-type formats is too wide for the single column it occupies.  If we expand the font size for those, the brackets `[]` extend into the column separator, becoming invisible.  If you can figure out a way to prevent that problem, then I'd support increasing the font size.

2024-08-31 23:05 UTC, aswaterman commented
Regarding the final issue (the caption appears in a strange place), I think that's because there's a page break.  See the following screenshot from the PDF rendered in Apple Preview.

I agree it's odd.  Ideally we would not break these figures across pages.  Perhaps @wmat can find a way to do that.

![Screenshot 2024-08-31 at 4 05 10 PM](https://github.com/user-attachments/assets/c41b31ec-883b-4ae1-b63b-e693e692c489)

2024-09-01 09:07 UTC, HepoH3 commented
You're remembering correctly, I understand that. However, this PR is not suggesting an increase in the font size for the B/J rows, but rather a decrease in the font size for the other rows, similar to what has already been done for Figure 2.4:

https://github.com/riscv/riscv-isa-manual/blob/8b9dc50e562af27c9ab22ae0a2d3bf528c6bd41d/src/images/wavedrom/immediate.edn#L7-L23.

2024-09-01 09:12 UTC, HepoH3 commented
> Regarding the final issue (the caption appears in a strange place), I think that's because there's a page break. See the following screenshot from the PDF rendered in Apple Preview.

I don't think page break cause this. I was referring to the v20240411 specification where I found this problem, but I think you checked some more recent versions of the specification, where this figure just happened to be positioned slightly higher. Last release renders in Firefox just like your screenshot. If we add something that pushes this figure back to page 24, the caption will still appear after the I-immediate:


![firefox_86HO04ueYm-1](https://github.com/user-attachments/assets/81eafef8-31ab-4924-a6c3-966674353448)


I can't check it in Apple Preview, but here is the [document itself](https://github.com/user-attachments/files/16828194/riscv-unprivileged.pdf)

Page breaking also doesn't explain why this figure is labeled as `Figure 1` (when it should be `Figure 2.4`). I can't see the captions for the nearest figures, so I think there's something wrong here.

2024-09-02 23:45 UTC, aswaterman commented
Yes, the page break is a coincidence.  Anyway, it would be good for @wmat to investigate why the caption shows up in an unexpected place.

2024-09-02 23:47 UTC, aswaterman commented
@wmat what do you think about the font-size proposal?  The effect is to make most of the text in the figure slightly more difficult to read, in exchange for consistency between the two figures.  I'll leave this to you.

2024-09-02 23:52 UTC, wmat commented
I will look i to this for you tomorrow. I know I played with font sizes at
some points to try to make text fir into boxes.  I’ll check on the missing
figure captions as well.

On Mon, Sep 2, 2024 at 7:47 PM Andrew Waterman ***@***.***>
wrote:

> @wmat <https://github.com/wmat> what do you think about the font-size
> proposal? The effect is to make most of the text in the figure slightly
> more difficult to read, in exchange for consistency between the two
> figures. I'll leave this to you.
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/riscv/riscv-isa-manual/pull/1620#issuecomment-2325388372>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AAAN6ZHRWP525KMOM5IP5B3ZUT2KHAVCNFSM6AAAAABNOCOUECVHI2DSMVQWIX3LMV43OSLTON2WKQ3PNVWWK3TUHMZDGMRVGM4DQMZXGI>
> .
> You are receiving this because you were mentioned.Message ID:
> ***@***.***>
>

2024-09-03 14:03 UTC, aswaterman commented
@wmat please separate them into separate PRs.  For now, I'll close this PR.

2024-09-03 14:03 UTC, closed without merging