Run docker as the current user
riscv/riscv-isa-manual pull request #1630
Opened 2024-09-06 08:16 UTC by Timmmm

If you have real Docker (not Podman) then by default it will run everything as root, so your build directory is owned by root and the Makefile will not work at all because it tries to modify the build directory.

This adds a flag so that Asciidoctor runs as the current user in Docker instead of root.

2024-09-09 02:26 UTC, aswaterman requested changes
This breaks the build on my Mac.

```
waterman@Andrews-Mac-mini:~/riscv-isa-manual$ make build/riscv-privileged.html
id: illegal option -- -
usage: id [user]
       id -A
       id -F [user]
       id -G [-n] [user]

       id -P [user]
       id -g [-nr] [user]
       id -p [user]
       id -u [-nr] [user]
rm -rf build/riscv-privileged.html.workdir && mkdir -p build/riscv-privileged.html.workdir && cp -r src docs-resources build/riscv-privileged.html.workdir
docker run --rm -v /Users/waterman/riscv-isa-manual/build/riscv-privileged.html.workdir:/build -w /build --user  riscvintl/riscv-docs-base-container-image:latest /bin/sh -c " LANG=C.utf8 asciidoctor --trace -a compress -a mathematical-format=svg -a pdf-fontsdir=docs-resources/fonts -a pdf-theme=docs-resources/themes/riscv-pdf.yml  -D build --failure-level=ERROR --require=asciidoctor-bibtex --require=asciidoctor-diagram --require=asciidoctor-lists --require=asciidoctor-mathematical src/riscv-privileged.adoc "
docker: invalid reference format.
See 'docker run --help'.
make: *** [build/riscv-privileged.html] Error 125
```

2024-09-09 08:39 UTC, Timmmm commented
Ah I guess Mac doesn't support `id --user`, only `id -u`. I changed it to the latter so it should work now (I don't have a Mac to test on unfortunately).

2024-09-10 01:01 UTC, merged

2024-09-23 18:02 UTC, wmat commented
Reverting for now as this breaks Linux builds, i.e. my local Fedora 40, as well as the GH workflow to release on merge.

2024-09-23 18:14 UTC, Timmmm commented
This didn't break the GH workflow to release on merge. That is still working, e.g. [here](https://github.com/riscv/riscv-isa-manual/actions/runs/10765489640). All of the failures are in forks which obviously shouldn't be able to publish new releases. (Maybe that step should be skipped for forks to make it less confusing...)

Also when you said you tried a clean checkout, did you actually delete the build directory or just do `git reset --hard`/`git checkout .`? I suspect what has happened is you have an old build directory from when Docker was running as root; now it isn't so it can't write to the build directory any more. Just deleting it should fix it.

Please can you confirm and re-apply this?

2024-09-23 18:17 UTC, Timmmm commented
> Actually this was after it merged

*before :-D

2024-09-23 18:25 UTC, wmat commented
Yep, I completely deleted the riscv-isa-manual repo locally and re-cloned it.  The issue occurred again.  Post revert, the broken GH workflow completed successfully.  See here: https://github.com/riscv/riscv-isa-manual/actions  I have to leave this reverted for now so that the merges successfully create releases when branches are merged.  But I'll continue to investigate.

2024-09-23 18:44 UTC, Timmmm commented
Can you point me to the failed GH workflow though? I can't see any unexpected failures.

Can you also tell me what command you are running that fails, and are you using Docker or Podman?

2024-09-23 18:52 UTC, wmat commented
Sure, here's a link to a failed workflow:  https://github.com/riscv/riscv-isa-manual/actions/runs/10986155225/job/30499080610

And here's the actual error:
`Run softprops/action-gh-release@v2
  with:
    tag_name: riscv-isa-release-78a4dc9-[2](https://github.com/riscv/riscv-isa-manual/actions/runs/10986155225/job/30499080610#step:14:2)024-09-2[3](https://github.com/riscv/riscv-isa-manual/actions/runs/10986155225/job/30499080610#step:14:3)
    name: Release riscv-isa-release-78a4dc9-202[4](https://github.com/riscv/riscv-isa-manual/actions/runs/10986155225/job/30499080610#step:14:4)-09-23
    draft: false
    prerelease: false
    make_latest: true
    generate_release_notes: true
    body: This release was created by: aswaterman
  Release of RISC-V ISA, built from commit [7](https://github.com/riscv/riscv-isa-manual/actions/runs/10986155225/job/30499080610#step:14:7)8a4dc9, is now available.
  
    files: /home/runner/work/riscv-isa-manual/riscv-isa-manual/build/riscv-privileged.pdf
  /home/runner/work/riscv-isa-manual/riscv-isa-manual/build/riscv-privileged.html
  /home/runner/work/riscv-isa-manual/riscv-isa-manual/build/riscv-privileged.epub
  /home/runner/work/riscv-isa-manual/riscv-isa-manual/build/riscv-unprivileged.pdf
  /home/runner/work/riscv-isa-manual/riscv-isa-manual/build/riscv-unprivileged.html
  /home/runner/work/riscv-isa-manual/riscv-isa-manual/build/riscv-unprivileged.epub
  
    token: ***
  env:
    SHORT_SHA: 7[8](https://github.com/riscv/riscv-isa-manual/actions/runs/10986155225/job/30499080610#step:14:8)a4dc9
    CURRENT_DATE: 2024-0[9](https://github.com/riscv/riscv-isa-manual/actions/runs/10986155225/job/30499080610#step:14:9)-23
    GITHUB_TOKEN: 
👩‍🏭 Creating new GitHub release for tag riscv-isa-release-78a4dc9-2024-09-23...
⚠️ GitHub release failed with status: 403
{"message":"Resource not accessible by integration","documentation_url":"https://docs.github.com/rest/releases/releases#create-a-release","status":"403"}
Skip retry — your GitHub token/PAT does not have the required permission to create a release
Error: Resource not accessible by integration - https://docs.github.com/rest/releases/releases#create-a-release`

Locally, I was simply running make.  It was erroring on permissions against the build directory.  And I'm using Docker.

2024-09-23 19:35 UTC, Timmmm commented
> `your GitHub token/PAT does not have the required permission to create a release`

Yeah that failure has nothing to do with this PR. It failed because it was running in a fork. Your recent workflow passed because it was not running in a fork:

![image](https://github.com/user-attachments/assets/ecb8448f-a474-4ae6-98d4-9d28436f3fec)

If you check the history of that action every run from a fork fails in the same way.

To debug the other issue (which sounds *very* strange; I'm also using Docker, and the distro shouldn't make a difference), can you run these commands and post the output?

```
id
id -u
docker --version
git clone https://github.com/riscv/riscv-isa-manual.git
cd riscv-isa-manual
git switch -d 3539eff338352aba83dbae9e7b310d6a7d9a7d56
make
ls -ld build
ls -l build
docker run --rm -v $(pwd)/build/riscv-privileged.pdf.workdir:/build:z -w /build riscvintl/riscv-docs-base-container-image:latest /bin/ls -ld /build
docker run --rm -v $(pwd)/build/riscv-privileged.pdf.workdir:/build:z -w /build riscvintl/riscv-docs-base-container-image:latest /bin/touch /build/foo
```

2024-09-23 19:37 UTC, Timmmm commented
Sorry, ignore the last two `docker` lines and do this instead:

```
docker run --rm -v $(pwd)/build/riscv-privileged.pdf.workdir:/build:z -w /build --user $(id -u) riscvintl/riscv-docs-base-container-image:latest /bin/ls -ld /build
docker run --rm -v $(pwd)/build/riscv-privileged.pdf.workdir:/build:z -w /build --user $(id -u) riscvintl/riscv-docs-base-container-image:latest /bin/touch /build/foo
docker run --rm -v $(pwd)/build/riscv-privileged.pdf.workdir:/build:z -w /build --user $(id -u) riscvintl/riscv-docs-base-container-image:latest /bin/id
```

2024-09-24 14:08 UTC, wmat commented
id
   uid=1000(wmat) gid=1000(wmat) groups=1000(wmat),10(wheel),18(dialout),976(docker) context=unconfined_u:unconfined_r:unconfined_t:s0-s0:c0.c1023
id -u
   1000
docker --version
   Docker version 27.3.1, build ce12230
git clone https://github.com/riscv/riscv-isa-manual.git
cd riscv-isa-manual
git switch -d 3539eff338352aba83dbae9e7b310d6a7d9a7d56
   HEAD is now at 3539eff3 Run docker as the current user (#1630)
make
   Checking if Docker is available...
Docker is available, building inside Docker container...
make[1]: Entering directory '/home/wmat/dev/riscv-isa-manual'
Starting build inside Docker container...
make build-docs
make[2]: Entering directory '/home/wmat/dev/riscv-isa-manual'
rm -rf build/riscv-privileged.pdf.workdir && mkdir -p build/riscv-privileged.pdf.workdir && cp -r src docs-resources build/riscv-privileged.pdf.workdir
docker run --rm -v /home/wmat/dev/riscv-isa-manual/build/riscv-privileged.pdf.workdir:/build -w /build --user 1000 riscvintl/riscv-docs-base-container-image:latest /bin/sh -c " LANG=C.utf8 asciidoctor-pdf --trace -a compress -a mathematical-format=svg -a pdf-fontsdir=docs-resources/fonts -a pdf-theme=docs-resources/themes/riscv-pdf.yml  -D build --failure-level=ERROR --require=asciidoctor-bibtex --require=asciidoctor-diagram --require=asciidoctor-lists --require=asciidoctor-mathematical src/riscv-privileged.adoc "
asciidoctor: ERROR: riscv-privileged.adoc: line 3: include file not found: /build/docs-resources/global-config.adoc
asciidoctor: ERROR: priv-preface.adoc: line 2: level 0 sections can only be used when doctype is book
asciidoctor: ERROR: images/bytefield/misareg.edn: line 2: Failed to generate image: Permission denied @ dir_s_mkdir - /build/images
asciidoctor: ERROR: images/bytefield/mvendorid.adoc: line 2: Failed to generate image: Permission denied @ dir_s_mkdir - /build/images
asciidoctor: ERROR: images/bytefield/marchid.adoc: line 2: Failed to generate image: Permission denied @ dir_s_mkdir - /build/images
asciidoctor: ERROR: images/bytefield/mimpid.adoc: line 2: Failed to generate image: Permission denied @ dir_s_mkdir - /build/images
asciidoctor: ERROR: images/bytefield/mhartid.adoc: line 2: Failed to generate image: Permission denied @ dir_s_mkdir - /build/images
asciidoctor: ERROR: images/wavedrom/mstatusreg-rv321.edn: line 3: Failed to generate image: Permission denied @ dir_s_mkdir - /build/images
asciidoctor: ERROR: images/wavedrom/mstatusreg.edn: line 3: Failed to generate image: Permission denied @ dir_s_mkdir - /build/images
asciidoctor: ERROR: images/wavedrom/mstatushreg.edn: line 3: Failed to generate image: Permission denied @ dir_s_mkdir - /build/images
asciidoctor: ERROR: images/bytefield/mtvec.adoc: line 2: Failed to generate image: Permission denied @ dir_s_mkdir - /build/images
asciidoctor: ERROR: images/bytefield/medeleg.adoc: line 2: Failed to generate image: Permission denied @ dir_s_mkdir - /build/images
asciidoctor: ERROR: images/bytefield/mideleg.adoc: line 2: Failed to generate image: Permission denied @ dir_s_mkdir - /build/images
asciidoctor: ERROR: images/bytefield/mideleg.adoc: line 2: Failed to generate image: Permission denied @ dir_s_mkdir - /build/images
asciidoctor: ERROR: images/bytefield/mideleg.adoc: line 2: Failed to generate image: Permission denied @ dir_s_mkdir - /build/images
asciidoctor: ERROR: images/bytefield/mipreg-standard.adoc: line 2: Failed to generate image: Permission denied @ dir_s_mkdir - /build/images
asciidoctor: ERROR: images/bytefield/miereg-standard.adoc: line 2: Failed to generate image: Permission denied @ dir_s_mkdir - /build/images
asciidoctor: ERROR: images/bytefield/hpmevents.adoc: line 2: Failed to generate image: Permission denied @ dir_s_mkdir - /build/images
asciidoctor: ERROR: images/bytefield/counteren.adoc: line 2: Failed to generate image: Permission denied @ dir_s_mkdir - /build/images
asciidoctor: ERROR: images/bytefield/counterinh.adoc: line 2: Failed to generate image: Permission denied @ dir_s_mkdir - /build/images
asciidoctor: ERROR: images/bytefield/mscratch.adoc: line 2: Failed to generate image: Permission denied @ dir_s_mkdir - /build/images
asciidoctor: ERROR: images/bytefield/mepcreg.adoc: line 2: Failed to generate image: Permission denied @ dir_s_mkdir - /build/images
asciidoctor: ERROR: images/bytefield/mcausereg.adoc: line 2: Failed to generate image: Permission denied @ dir_s_mkdir - /build/images
asciidoctor: ERROR: images/bytefield/mtvalreg.adoc: line 2: Failed to generate image: Permission denied @ dir_s_mkdir - /build/images
asciidoctor: ERROR: images/bytefield/mconfigptrreg.adoc: line 2: Failed to generate image: Permission denied @ dir_s_mkdir - /build/images
asciidoctor: ERROR: images/wavedrom/menvcfgreg.edn: line 3: Failed to generate image: Permission denied @ dir_s_mkdir - /build/images
asciidoctor: ERROR: images/wavedrom/mseccfg.edn: line 3: Failed to generate image: Permission denied @ dir_s_mkdir - /build/images
asciidoctor: ERROR: images/bytefield/mtime.adoc: line 2: Failed to generate image: Permission denied @ dir_s_mkdir - /build/images
asciidoctor: ERROR: images/bytefield/mtimecmp.adoc: line 2: Failed to generate image: Permission denied @ dir_s_mkdir - /build/images
asciidoctor: ERROR: images/wavedrom/mm-env-call.edn: line 5: Failed to generate image: Permission denied @ dir_s_mkdir - /build/images
asciidoctor: ERROR: images/wavedrom/trap-return.edn: line 5: Failed to generate image: Permission denied @ dir_s_mkdir - /build/images
asciidoctor: ERROR: images/wavedrom/wfi.edn: line 5: Failed to generate image: Permission denied @ dir_s_mkdir - /build/images
asciidoctor: ERROR: images/bytefield/cust-sys-instr.adoc: line 2: Failed to generate image: Permission denied @ dir_s_mkdir - /build/images
asciidoctor: ERROR: images/bytefield/pmp-rv32.adoc: line 2: Failed to generate image: Permission denied @ dir_s_mkdir - /build/images
asciidoctor: ERROR: images/bytefield/pmp-rv64.adoc: line 2: Failed to generate image: Permission denied @ dir_s_mkdir - /build/images
asciidoctor: ERROR: images/bytefield/pmpaddr-rv32.adoc: line 2: Failed to generate image: Permission denied @ dir_s_mkdir - /build/images
asciidoctor: ERROR: images/bytefield/pmpaddr-rv64.adoc: line 2: Failed to generate image: Permission denied @ dir_s_mkdir - /build/images
asciidoctor: ERROR: images/bytefield/pmpcfg.adoc: line 2: Failed to generate image: Permission denied @ dir_s_mkdir - /build/images
asciidoctor: ERROR: smstateen.adoc: line 180: Failed to generate image: Permission denied @ dir_s_mkdir - /build/images
asciidoctor: ERROR: smstateen.adoc: line 199: Failed to generate image: Permission denied @ dir_s_mkdir - /build/images
asciidoctor: ERROR: smstateen.adoc: line 217: Failed to generate image: Permission denied @ dir_s_mkdir - /build/images
asciidoctor: ERROR: images/bytefield/mnscratch.adoc: line 2: Failed to generate image: Permission denied @ dir_s_mkdir - /build/images
asciidoctor: ERROR: images/bytefield/mnepc.edn: line 2: Failed to generate image: Permission denied @ dir_s_mkdir - /build/images
asciidoctor: ERROR: images/bytefield/mncause.edn: line 2: Failed to generate image: Permission denied @ dir_s_mkdir - /build/images
asciidoctor: ERROR: images/bytefield/mnstatus.edn: line 2: Failed to generate image: Permission denied @ dir_s_mkdir - /build/images
asciidoctor: ERROR: supervisor.adoc: line 49: Failed to generate image: Permission denied @ dir_s_mkdir - /build/images
asciidoctor: ERROR: supervisor.adoc: line 76: Failed to generate image: Permission denied @ dir_s_mkdir - /build/images
asciidoctor: ERROR: images/bytefield/stvec.edn: line 2: Failed to generate image: Permission denied @ dir_s_mkdir - /build/images
asciidoctor: ERROR: images/bytefield/sip.edn: line 2: Failed to generate image: Permission denied @ dir_s_mkdir - /build/images
asciidoctor: ERROR: images/bytefield/sie.edn: line 2: Failed to generate image: Permission denied @ dir_s_mkdir - /build/images
asciidoctor: ERROR: images/bytefield/sipreg-standar [...]

2024-09-24 15:44 UTC, Timmmm commented
Ah I think maybe you're running rootless docker? What's the output of this command?

```
docker info -f '{{println .SecurityOptions}}'
```

2024-09-24 16:52 UTC, wmat commented
I am indeed running it rootless:
[name=seccomp,profile=builtin name=rootless name=cgroupns]

I believe when I set it up I followed the instructions here: https://docs.docker.com/engine/install/linux-postinstall/

2024-09-25 08:18 UTC, Timmmm commented
@wmat can you check if #1647 works for you?