Add basic support for tagging text in the spec
riscv/riscv-isa-manual pull request #1769
Opened 2024-12-11 18:12 UTC by Timmmm

This adds three things:
    
1. Custom CSS to add a subtle dotted underline on hover to any element with an ID starting with `manual__`.
2. An example tag `manual__x0_is_zero`, tagging the text that specifies that x0 is hardwired to 0.
3. A way of extracting the text of the tags into JSON.
    
This just adds a single tag as an example, but the intention is that such tags would be added throughout the spec, allowing coverage, test plans, tests, documentation, etc. to all link to specific parts of the spec.

See #1397

2024-12-11 18:12 UTC, Timmmm commented
It looks like this (when hovered):

![image](https://github.com/user-attachments/assets/d806ae10-aa38-4455-bd82-4db6c3f5ad73)

2025-02-14 22:56 UTC, james-ball-qualcomm reviewed
Will this tags.rb work for all adoc anchor types:

- This is before the parameter definition. [#param-foo-1]#Here's a parameter defined using inline anchors.# This is after the parameter definition.
- [#param-foo-2]
Here's a parameter defined in its own block using the # ID syntax.
- [[param-foo-3]]
Here's a parameter defined using an anchor.

2025-02-14 22:56 UTC, james-ball-qualcomm commented on .gitmodules
> +	url = https://github.com/Timmmm/docs-resources
Do you really want to merge in this change? Shouldn't be be using the riscv and not the Timmmm submodule?

2025-02-14 22:56 UTC, james-ball-qualcomm commented on src/docinfo.html
> +Any ID starting with 'qx_' (arbitrarily chosen to be unlikely to
I thought we had settled on the "manual:" prefix. Can we use that instead of "qx_"? Will this cause any problems for the manual:priv and manual:unpriv anchors I recently added to the first block of the priv and unpriv manuals respectively (they used to have the same anchor name which doesn't work well when both priv and unpriv are in the same book). See #1841 for details.

2025-02-27 13:37 UTC, Timmmm commented on .gitmodules
> +	url = https://github.com/Timmmm/docs-resources
No, this was meant to be temporary just so it would pass CI. I'll make a PR for `docs-resources` later (yeay submodules!).

2025-02-27 13:37 UTC, Timmmm commented on src/docinfo.html
> +Any ID starting with 'qx_' (arbitrarily chosen to be unlikely to
Ah yeah I just haven't got around to updating it to `manual:` I will do that.

2025-07-14 17:00 UTC, Timmmm commented on src/docinfo.html
> +Any ID starting with 'qx_' (arbitrarily chosen to be unlikely to
Updated to `manual__`. I didn't use `manual:` because these end up in XML IDs if you use the docbook output and `:` is not invalid in an XML ID.

2025-07-14 17:02 UTC, Timmmm commented
This came up again in the Sail meeting. Can we get some progress towards merging this? Or at least a decision like "if this has tags for a significant part of the base chapters etc. then it can be merged"?

> Will this tags.rb work for all adoc anchor types:

Yeah I believe so, or we can make it work if it doesn't.

2025-07-14 17:04 UTC, Timmmm commented on .gitmodules
> +	url = https://github.com/Timmmm/docs-resources
Corresponding PR: https://github.com/riscv/docs-resources/pull/47

2025-07-14 21:42 UTC, james-ball-qualcomm commented
Last week without remember this PR, I created a Ruby script to extract all normative rule anchors and their associated text from the ISA manuals into a YAML file. It does this by using a CSS selector to find anchors in the ISA manual HTML files. I see Tim has instead created a new adoc backend in docs-resources/converters/tags.rb to do something similar but into JSON. Let me take a look at this approach.

My Ruby script relies on my naming convention which is documented in a UDB file at the moment. This is just a temporary home and so I've copied the documentation below. You'll see my naming convention is that anything anchor that starts with "norm:" is used by ISA manual normative rules that we are creating in the CSC (and will review with TSC). I have another Ruby script that performs an intelligent compare between the normative rule anchors in a workspace and a reference. I'd integrate both of these Ruby scripts into the ISA manual Makefile and then we could have github actions that complain if you try to remove or edit the text in a normative rule anchor.


Others potentially interested in this PR:
- @dhower-qc 
- @jrgrimm11

```
# Copyright (c) Qualcomm Technologies, Inc. and/or its subsidiaries.
# SPDX-License-Identifier: BSD-3-Clause-Clear

# frozen_string_literal: true

# Creates links into RISC-V documentation with the following formats for the destination link.
# 
#   Documentation Format                                                  Applies
#   ============  ======================================================= ================================================
#   ISA manuals   norm:base:<base-name>:<identifier>                      Single base ISA (rv32i/rv32e/rv64i)
#                 norm:bases<base-name>[_<base-name>]+:<identifier>       List of bases separated by "_"
#                 norm:basegrp:<group-name>:<identifier>                  Named group of bases (e.g., rv32, all)
#                 norm:ext:<ext-name>:<identifier>                        Single extension
#                 norm:exts:<ext-name>[_<ext-name>]:<identifier>          List of extensions separated by "_"
#                 norm:extgrp:<ext-name>:<identifier>                     Named group of extensions
#                 norm:enc:insttable:<inst-name>                          Instruction table cell for instruction encoding
#                 norm:inst:<inst-name>:<identifier>                      Single instruction
#                 norm:insts:<inst-name>[_<inst-name>]+:<identifier>      List of instructions separated by "_"
#                 norm:instgrp:<group-name>:<identifier>                  Named group of insts (e.g., branch, load, store, etc.)
#                 norm:csr:<csr-name>:<identifier>                        Single CSR
#                 norm:csr_field:<csr-name>:<field-name>:<identifier>     Single CSR field
#                 norm:param:<ext-name>:<param-name>:<identifier>
#                   where <identifier> is a string that describes the tagged text
#   UDB encoding  udb:enc:inst:<inst-name>
#   UDB doc       udb:doc:ext:<ext-name>
#                 udb:doc:inst:<inst-name>
#                 udb:doc:csr:<csr-name>
#                 udb:doc:csr_field:<csr-name>:<field-name>
#                 udb:doc:param:<ext-name>:<param-name>
#                 udb:doc:func:<func-name>  (Documentation of common/built-in IDL functions)
#                 udb:doc:covpt:<org>:<id>
#                   where <org> is:
#                      sep for UDB documentation that "separates" normative rules from test plans
#                      combo for UDB documentation that "combines" normative rules with test plans
#                      appendix for UDB documentation that has normative rules and test plans in appendices
#                   where <id> is the ID of the normative rule
#   IDL code      idl:code:inst:<inst-name>:<location>
#                 TODO for CSR and CSR Fields
#
# Use underscores to replace blanks in names between colons since RISC-V uses minus signs in the names.
#
# Adding anchors into AsciiDoc files
# ==================================
#  1) Anchor to part of a paragraph
#     Syntax:      [#<anchor-name>]# ... #
#     Example:     Here is an example of [#foo]#anchoring part# of a paragraph
#                  and can have [#bar]#multiple anchors# if needed.
#     Tagged text: "anchoring part" and "multiple anchors"
#     HTML:        <div class="paragraph">
#                  <p>Here is an example of <span id="foo">anchoring part</span> of a paragraph
#                  and can have <span id="bar">multiple anchors</span> if needed.</p>
#                  </div>
#     Example:    [#monkey]#Anchoring part of a paragraph#
#                 [#zebra]#and can have multiple anchors# if needed.
#                 and create a span for each one.
#     HTML:       <div class="paragraph">
#                 <p><span id="monkey">Anchoring part of a paragraph</span>
#                 <span id="zebra">and can have multiple anchors</span> if needed.
#                 and create a span for each one.</p>
#                 </div>
#     Limitations:
#       - Can't anchor text across multiple paragraphs.
#       - Must have text next to the 2nd hash symbol (i.e., can't have newline after [#<anchor-name]#).
#       - Can't put inside admonitions such as [NOTE] (see #3 below for solution).
#
#  2) Anchor to entire paragraph
#     Syntax:     [[<anchor-name]]
#     Example:    [[zort]]
#                 Here is an example of anchoring a whole paragraph.
#     Tagged text: Entire paragraph
#     HTML:       <div id="zort" class="paragraph">
#                 <p>Here is an example of anchoring a whole paragraph.</p>
#                 </div>
#
#  3) Anchor inside admonition (e.g. [NOTE])
#     - Must use [[<anchor-name]] before each paragraph (with unique anchor names of course) being tagged
#     - Can't use [#<anchor-name]## since it just shows up in HTML as normal text
#     - Don't put [[<<anchor-name]] anchor before admonition to apply to entire admonition (one or more paragraphs)
#       since the HTML won't tag the text, just its location.
#
#  4) Anchor in table cell
#     - Must use [[<anchor-name]] after "|" and before cell contents and will tag all text in the cell.
#     Example:    |===
#                 |name|number
#
#                 |Bob|[[BobNumber]]415-555-1212
#                 |Pat| [[PatNumber]]  408-555-1212
#                 |===
#     Tagged text: "415-555-1212" and "  408-555-1212"
#     HTML:       <tr>
#                 <td class="tableblock"><p class="tableblock">Bob</p></td>
#                 <td class="tableblock"><p class="tableblock"><a id="BobNumber"></a>413-555-1212</p></td>
#                 </tr>
#                 <tr>
#                 <td class="tableblock"><p class="tableblock">Pat</p></td>
#                 <td class="tableblock"><p class="tableblock"><a id="PatNumber"></a>  408-555-1212</p></td>
#                 </tr>

2025-07-14 21:52 UTC, james-ball-qualcomm commented
At first blush, Tim's approach of using a new adoc backend looks better than my approach of parsing the HTML. I tried using the Ruby adoc API but discovered the inline anchors aren't expanded by the API so switched to the HTML approach. 

Time, does your adoc backend approach handle all the cases listed in my naming scheme? That would be paragraph anchors, inline anchors, anchors to table cells, and anchors to text inside admonitions? Also, I'll need the section number that the anchor is located in. I don't currently support that yet in my anchor extraction Ruby script but was about to add it. Tim, can you support that with your adoc backend?

2025-07-15 10:06 UTC, Timmmm commented
> Tim's approach of using a new adoc backend looks better than my approach of parsing the HTML. 

Yeah I also started by parsing the docbook XML output, but decided it would be better to do it properly via an Asciidoctor backend. It's definitely better.

> Tim, does your adoc backend approach handle all the cases listed in my naming scheme? 

Yes these all work, though note that for table cells this doesn't quite work:

> Must use [[<anchor-name>]] after "|" and before cell contents and will tag all text in the cell.

This actually tags an empty paragraph at the start of the cell for some reason. However using `[#<anchor>]#...#` works fine in a table cell.

I pushed a commit that demonstrates all of these things.

>  I'll need the section number that the anchor is located in. 

Yeah I was also thinking this would be really useful. My plan was to add a section hierarchy to the JSON listing all the tags in each section like this:

```
{
    "sections": [
       {
          "title": "Introduction",
          "html_anchor": "_introduction",
          "children": [
              {
                  "title": "RISC-V Hardware Platform Terminology",
                  "html_anchor": "_risc_v_hardware_platform_terminology",
                  "tags": ["manual__foo", "manual__bar", ...]
...
     ],
     "tags": {
          "manual_foo": "Foo is a nonsense word used for...
     }
}
```

This allows you to present the tags more nicely, and obviates some of the reasons for putting a ton of grouping metadata in the tags. I don't think people are going to want to use this if they have to write tags like `[#norm__insts__andi_ori_xori__imm_is_sign_extended]` or whatever. Eh maybe that's not awful. Anyway we should probably bike shed the naming later.

Does that `"sections":` schema seem reasonable?

2025-07-17 00:37 UTC, james-ball-qualcomm commented
I've confirmed that inline anchors in table cells work fine. Then you get a span containing the cell contents instead of no contents which seems better. Don't know why I thought inline anchors didn't work well in table cells.

2025-07-17 04:11 UTC, james-ball-qualcomm commented
I think I'll setup a meeting to discuss this live.

2025-07-18 22:04 UTC, james-ball-qualcomm requested changes
Pretty sure you want to back-out this change to .gitmodules now that your tag backend PR has been merged.

2025-07-18 22:16 UTC, james-ball-qualcomm commented
I gave this a spin and got a pretty reasonable looking JSON file after changing the prefix to "norm:" in the Makefile (in my local workspace, not in this PR):

```
{
  "tags": {
    "norm:basegrp:rv32:xregwidth": "For RV32I, the 32 x registers are each 32 bits wide,\ni.e., XLEN=32.",
    "norm:basegrp:all:x0eq0": "Register x0 is hardwired with all bits equal to 0.",
    "norm:bases:rv32i_rv64i:other-xregs": "General purpose registers x1-x31 hold values that various\ninstructions interpret as a collection of Boolean values, or as two's\ncomplement signed binary integers or unsigned binary integers.",
    "norm:basegrp:all:pcreg": "There is one additional unprivileged register: the program counter pc\nholds the address of the current instruction.",
    "norm:instgrp:taken_cti:ia_misaligned_exc": "An instruction-address-misaligned exception is generated on a taken branch\nor unconditional jump if the target address is not IALIGN-bit aligned.\nThis exception is reported on the branch or jump instruction, not on the target instruction.",
    "norm:instgrp:cond_branch:no_ia_misaligned_exc_not_taken": "No instruction-address-misaligned exception is generated\nfor a conditional branch that is not taken.",
    "norm:basegrp:all:imm_always_sex": "immediates are always sign-extended",
    "norm:inst:addi:operation": "ADDI adds the sign-extended 12-bit immediate to register rs1.",
    "norm:inst:addi:overflow": "Arithmetic overflow is ignored and the result is simply the low XLEN bits of the result.",
    "norm:insts:slti_sltiu:operation": "SLTI (set less than immediate) places the value 1 in register rd if\nregister rs1 is less than the sign-extended immediate when both are\ntreated as signed numbers, else 0 is written to rd. SLTIU is similar\nbut compares the values as unsigned numbers (i.e., the immediate is\nfirst sign-extended to XLEN bits then treated as an unsigned number).",
    "norm:insts:andi_ori_xori:operation": "ANDI, ORI, XORI are logical operations that perform bitwise AND, OR, and\nXOR on register rs1 and the sign-extended 12-bit immediate and place\nthe result in rd.",
    "norm:inst:slli:operation": "SLLI is a logical left shift (zeros are shifted into the lower bits);",
    "norm:inst:srli:operation": "SRLI is a logical right shift (zeros are shifted into the upper bits);",
    "norm:inst:srai:operation": "SRAI is an arithmetic right shift (the original sign bit is copied into the vacated upper bits).",
    "norm:inst:lui:operation": "LUI places the 32-bit U-immediate value into the\ndestination register rd, filling in the lowest 12 bits with zeros.",
    "norm:inst:auipc:operation": "AUIPC forms a 32-bit offset from\nthe U-immediate, filling in the lowest 12 bits with zeros, adds this\noffset to the address of the AUIPC instruction, then places the result\nin register rd.",
    "norm:basegrp:all:R-type_operands": "All operations read\nthe rs1 and rs2 registers as source operands and write the result into register rd.",
    "norm:inst:add:operation": "ADD performs the addition of rs1 and rs2.",
    "norm:inst:sub:operation": "SUB performs the subtraction of rs2 from rs1.",
    "norm:insts:add_sub:overflow": "Overflows are ignored and the low XLEN bits of results are written to the destination rd.",
    "norm:insts:slt_sltu:operation": "SLT and SLTU perform signed and unsigned compares respectively, writing 1 to rd if\nrs1 &lt; rs2, 0 otherwise.",
    "norm:insts:and_or_xor:operation": "AND, OR, and XOR perform bitwise logical operations.",
    "norm:insts:sll_srl_sra:operation": "SLL, SRL, and SRA perform logical left, logical right, and arithmetic\nright shifts on the value in register rs1 by the shift amount held in\nthe lower 5 bits of register rs2.",
    "norm:instgrp:cti:no_cti_delay_slots": "Control transfer instructions in RV32I\ndo not have architecturally visible delay slots.",
    "norm:instgrp:cti:ia_fault_exc_on_target": "If an instruction access-fault or instruction page-fault exception\noccurs on the target of a jump or taken branch, the exception is\nreported on the target instruction, not on the jump or branch instruction.",
    "norm:inst:jal:target": "The offset is sign-extended and added to the address of the jump instruction to\nform the jump target address.",
    "norm:inst:jal:operation": "JAL stores the address of the instruction\nfollowing the jump ('pc'+4) into register rd.",
    "norm:inst:jalr:target": "The target address is obtained by adding the\nsign-extended 12-bit I-immediate to the register rs1, then setting the\nleast-significant bit of the result to zero.",
    "norm:inst:jalr:operation": "The address of the\ninstruction following the jump (pc+4) is written to register rd.",
    "norm:instgrp:branch:target": "The 12-bit B-immediate encodes signed offsets in multiples of 2 bytes. The offset\nis sign-extended and added to the address of the branch instruction to give the target address.",
    "norm:insts:beq_bne:operation": "BEQ and BNE take the branch if registers rs1 and rs2 are equal or unequal respectively.",
    "norm:insts:blt_bltu:operation": "BLT and BLTU take the branch if rs1 is less than rs2, using signed and\nunsigned comparison respectively.",
    "norm:insts:bge_bgeu:operation": "BGE and BGEU take the branch if rs1 is greater than or equal to rs2,\nusing signed and unsigned comparison respectively.",
    "norm:instgrp:load:exc_x0": "Loads with a destination of\nx0 must still raise any exceptions and cause any other side effects\neven though the load value is discarded.",
    "norm:param:I:endianness:little_or_big": "The EEI will define whether the memory system is little-endian or big-endian.",
    "norm:instgrp:load_store:endian_byte_invariant": "In RISC-V, endianness is byte-address invariant.",
    "norm:instgrp:load_store:endian_byte_operation": "In a system for which endianness is byte-address invariant, the\nfollowing property holds: if a byte is stored to memory at some address\nin some endianness, then a byte-sized load from that address in any\nendianness returns the stored value.",
    "norm:instgrp:load_store:little_endian_operation": "In a little-endian configuration, multibyte stores write the\nleast-significant register byte at the lowest memory byte address,\nfollowed by the other register bytes in ascending order of their\nsignificance. Loads similarly transfer the contents of the lesser memory\nbyte addresses to the less-significant register bytes.",
    "norm:instgrp:load_store:big_endian_operation": "In a big-endian configuration, multibyte stores write the\nmost-significant register byte at the lowest memory byte address,\nfollowed by the other register bytes in descending order of their\nsignificance. Loads similarly transfer the contents of the greater\nmemory byte addresses to the less-significant register bytes.",
    "norm:instgrp:load_store:ea": "The effective address is obtained by adding register rs1 to the\nsign-extended 12-bit offset.",
    "norm:instgrp:load:operation": "Loads copy a value from memory to register rd.",
    "norm:instgrp:store:operation": "Stores copy the value in register rs2 to memory.",
    "norm:inst:lw:operation": "The LW instruction loads a 32-bit value from memory into rd.",
    "norm:inst:lh:operation": "LH loads a 16-bit value from memory, then sign-extends to 32-bits before storing\nin rd.",
    "norm:inst:lhu:operation": "LHU loads a 16-bit value from memory but then zero extends to\n32-bits before storing in rd.",
    "norm:insts:lb_lbu:operation": "LB and LBU are defined analogously for 8-bit values.",
    "norm:insts:sw_sh_sb:operation": "The SW, SH, and SB instructions store 32-bit, 16-bit, and\n8-bit values from the low bits of register rs2 to memory.",
    "norm:instgrp:load_store:no_exc_aligned": "loads and stores whose effective addresses are\nnaturally aligned shall not raise an address-misaligned exception.",
    "norm:param:I:misaligned_ldst:eei_dependent_behavior": "Loads and stores whose effective address is not naturally ali [...]

2025-07-18 22:24 UTC, james-ball-qualcomm commented
Here's what my Ruby script that parses the HTML to get the tags produces (a slightly out of date version):

```
---
version: 1.0
anchors:
- type: Inline
  name: norm:basegrp:rv32:xregwidth
  text: |-
    For RV32I, the 32 x registers are each 32 bits wide,
    i.e., XLEN=32.
- type: Inline
  name: norm:basegrp:all:x0eq0
  text: Register x0 is hardwired with all bits equal to 0.
- type: Inline
  name: norm:bases:rv32i_rv64i:other-xregs
  text: |-
    General purpose registers x1-x31 hold values that various
    instructions interpret as a collection of Boolean values, or as two’s
    complement signed binary integers or unsigned binary integers.
- type: Paragraph
  name: norm:basegrp:all:pcreg
  text: |
    There is one additional unprivileged register: the program counter pc
    holds the address of the current instruction.
- type: Inline
  name: norm:instgrp:taken_cti:ia_misaligned_exc
  text: |-
    An instruction-address-misaligned exception is generated on a taken branch
    or unconditional jump if the target address is not IALIGN-bit aligned.
    This exception is reported on the branch or jump instruction, not on the target instruction.
- type: Inline
  name: norm:instgrp:cond_branch:no_ia_misaligned_exc_not_taken
  text: |-
    No instruction-address-misaligned exception is generated
    for a conditional branch that is not taken.
- type: Inline
  name: norm:basegrp:all:imm_always_sex
  text: immediates are always sign-extended
- type: Inline
  name: norm:inst:addi:operation
  text: ADDI adds the sign-extended 12-bit immediate to register rs1.
- type: Inline
  name: norm:inst:addi:overflow
  text: Arithmetic overflow is ignored and the result is simply the low XLEN bits
    of the result.
- type: Inline
  name: norm:insts:slti_sltiu:operation
  text: |-
    SLTI (set less than immediate) places the value 1 in register rd if
    register rs1 is less than the sign-extended immediate when both are
    treated as signed numbers, else 0 is written to rd. SLTIU is similar
    but compares the values as unsigned numbers (i.e., the immediate is
    first sign-extended to XLEN bits then treated as an unsigned number).
- type: Inline
  name: norm:insts:andi_ori_xori:operation
  text: |-
    ANDI, ORI, XORI are logical operations that perform bitwise AND, OR, and
    XOR on register rs1 and the sign-extended 12-bit immediate and place
    the result in rd.
- type: Inline
  name: norm:inst:slli:operation
  text: SLLI is a logical left shift (zeros are shifted into the lower bits);
- type: Inline
  name: norm:inst:srli:operation
  text: SRLI is a logical right shift (zeros are shifted into the upper bits);
- type: Inline
  name: norm:inst:srai:operation
  text: SRAI is an arithmetic right shift (the original sign bit is copied into the
    vacated upper bits).
- type: Inline
  name: norm:inst:lui:operation
  text: |-
    LUI places the 32-bit U-immediate value into the
    destination register rd, filling in the lowest 12 bits with zeros.
- type: Inline
  name: norm:inst:auipc:operation
  text: |-
    AUIPC forms a 32-bit offset from
    the U-immediate, filling in the lowest 12 bits with zeros, adds this
    offset to the address of the AUIPC instruction, then places the result
    in register rd.
- type: Inline
  name: norm:basegrp:all:R-type_operands
  text: |-
    All operations read
    the rs1 and rs2 registers as source operands and write the result into register rd.
- type: Inline
  name: norm:inst:add:operation
  text: ADD performs the addition of rs1 and rs2.
- type: Inline
  name: norm:inst:sub:operation
  text: SUB performs the subtraction of rs2 from rs1.
- type: Inline
  name: norm:insts:add_sub:overflow
  text: Overflows are ignored and the low XLEN bits of results are written to the
    destination rd.
- type: Inline
  name: norm:insts:slt_sltu:operation
  text: |-
    SLT and SLTU perform signed and unsigned compares respectively, writing 1 to rd if
    rs1 < rs2, 0 otherwise.
- type: Inline
  name: norm:insts:and_or_xor:operation
  text: AND, OR, and XOR perform bitwise logical operations.
- type: Inline
  name: norm:insts:sll_srl_sra:operation
  text: |-
    SLL, SRL, and SRA perform logical left, logical right, and arithmetic
    right shifts on the value in register rs1 by the shift amount held in
    the lower 5 bits of register rs2.
- type: Inline
  name: norm:instgrp:cti:no_cti_delay_slots
  text: |-
    Control transfer instructions in RV32I
    do not have architecturally visible delay slots.
- type: Inline
  name: norm:instgrp:cti:ia_fault_exc_on_target
  text: |-
    If an instruction access-fault or instruction page-fault exception
    occurs on the target of a jump or taken branch, the exception is
    reported on the target instruction, not on the jump or branch instruction.
- type: Inline
  name: norm:inst:jal:target
  text: |-
    The offset is sign-extended and added to the address of the jump instruction to
    form the jump target address.
- type: Inline
  name: norm:inst:jal:operation
  text: |-
    JAL stores the address of the instruction
    following the jump ('pc'+4) into register rd.
- type: Inline
  name: norm:inst:jalr:target
  text: |-
    The target address is obtained by adding the
    sign-extended 12-bit I-immediate to the register rs1, then setting the
    least-significant bit of the result to zero.
    [#norm:inst:jalr:operation]#The address of the
    instruction following the jump (pc+4) is written to register rd.
- type: Inline
  name: norm:instgrp:branch:target
  text: |-
    The 12-bit B-immediate encodes signed offsets in multiples of 2 bytes. The offset
    is sign-extended and added to the address of the branch instruction to give the target address.
- type: Inline
  name: norm:insts:beq_bne:operation
  text: BEQ and BNE take the branch if registers rs1 and rs2 are equal or unequal
    respectively.
- type: Inline
  name: norm:insts:blt_bltu:operation
  text: |-
    BLT and BLTU take the branch if rs1 is less than rs2, using signed and
    unsigned comparison respectively.
- type: Inline
  name: norm:insts:bge_bgeu:operation
  text: |-
    BGE and BGEU take the branch if rs1 is greater than or equal to rs2,
    using signed and unsigned comparison respectively.
- type: Inline
  name: norm:instgrp:load:exc_x0
  text: |-
    Loads with a destination of
    x0 must still raise any exceptions and cause any other side effects
    even though the load value is discarded.
- type: Inline
  name: norm:param:I:endianness:little_or_big
  text: The EEI will define whether the memory system is little-endian or big-endian.
- type: Inline
  name: norm:instgrp:load_store:endian_byte_invariant
  text: In RISC-V, endianness is byte-address invariant.
- type: Paragraph
  name: norm:instgrp:load_store:endian_byte_operation
  text: |
    In a system for which endianness is byte-address invariant, the
    following property holds: if a byte is stored to memory at some address
    in some endianness, then a byte-sized load from that address in any
    endianness returns the stored value.
- type: Paragraph
  name: norm:instgrp:load_store:little_endian_operation
  text: |
    In a little-endian configuration, multibyte stores write the
    least-significant register byte at the lowest memory byte address,
    followed by the other register bytes in ascending order of their
    significance. Loads similarly transfer the contents of the lesser memory
    byte addresses to the less-significant register bytes.
- type: Paragraph
  name: norm:instgrp:load_store:big_endian_operation
  text: |
    In a big-endian configuration, multibyte stores write the
    most-significant register byte at the lowest memory byte address,
    followed by the other register bytes in descending order of their
    significance. Loads similarly transfer the contents of the greater
    memory byte addresses to the less-significant register bytes.
- type: Inline
  name: norm:instgrp:load_store:ea
  text: |-
    The effective address is obtained by [...]

2025-07-18 22:37 UTC, james-ball-qualcomm commented on Makefile
> +           -a docinfo=shared \
Seems like changes to add the dotted underscores should be in a different PR.

2025-07-18 22:38 UTC, james-ball-qualcomm commented on Makefile
> +           -a tags-prefix=manual__ \
Do we really want the "manual__" prefix in the Makefile? For example, my anchors (AKA tags) use a "norm:" prefix.

2025-07-18 22:43 UTC, james-ball-qualcomm commented on Makefile
> +           -a tags-prefix=manual__ \
Instead we could pass in the prefix on the makefile command line with "make TAGS_PREFIX=value" and changing the makefile to say "-a tags-prefix=$(TAGS_PREFIX)" or something of that sort?

2025-07-24 17:40 UTC, james-ball-qualcomm commented on .gitmodules
> +	url = https://github.com/Timmmm/docs-resources
Don't you need to remove this change from the PR?

2025-09-01 12:25 UTC, Timmmm commented
Merged in #2195

2025-09-01 12:25 UTC, closed without merging